version: '3.8'

services:
  # 1. Mensageria
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: pulse_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: pulse_admin
      RABBITMQ_DEFAULT_PASS: pulse_secure2026
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pulse_net

  # 2. Banco Primário
  db-primary:
    image: postgres:15-alpine
    container_name: pulse_db_primary
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_secure2026
      POSTGRES_DB: pulsealert
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_admin -d pulsealert"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - pulse_net

  # 3. Banco Réplica
  db-replica:
    image: postgres:15-alpine
    container_name: pulse_db_replica
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: db_secure2026
      POSTGRES_DB: pulsealert
    volumes:
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5433:5432" # Expõe externamente na 5433, mas internamente o Postgres roda na 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_admin -d pulsealert"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - pulse_net

  # 4. Gateway (Produtor gRPC)
  gateway:
    build:
      context: ./pulsealert-gateway
    container_name: pulse_gateway
    ports:
      - "9090:9090"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - GRPC_SERVER_PORT=9090
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - pulse_net

  # 5. Workers (Consumidores e Eleição)
  worker1:
    build:
      context: ./pulsealert-worker
    container_name: pulse_worker1
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db-primary
      - WORKER_ID=1
      - WORKER_NEXT_URL=http://worker2:8080
      - SPRING_DATASOURCE_PRIMARY_JDBC_URL=jdbc:postgresql://db-primary:5432/pulsealert
      - SPRING_DATASOURCE_PRIMARY_USERNAME=db_admin
      - SPRING_DATASOURCE_PRIMARY_PASSWORD=db_secure2026
      - SPRING_DATASOURCE_REPLICA_JDBC_URL=jdbc:postgresql://db-replica:5432/pulsealert
      - SPRING_DATASOURCE_REPLICA_USERNAME=db_admin
      - SPRING_DATASOURCE_REPLICA_PASSWORD=db_secure2026
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-primary:
        condition: service_healthy
      db-replica:
        condition: service_healthy
    networks:
      - pulse_net

  worker2:
    build:
      context: ./pulsealert-worker
    container_name: pulse_worker2
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db-primary
      - WORKER_ID=2
      - WORKER_NEXT_URL=http://worker3:8080
      - SPRING_DATASOURCE_PRIMARY_JDBC_URL=jdbc:postgresql://db-primary:5432/pulsealert
      - SPRING_DATASOURCE_PRIMARY_USERNAME=db_admin
      - SPRING_DATASOURCE_PRIMARY_PASSWORD=db_secure2026
      - SPRING_DATASOURCE_REPLICA_JDBC_URL=jdbc:postgresql://db-replica:5432/pulsealert
      - SPRING_DATASOURCE_REPLICA_USERNAME=db_admin
      - SPRING_DATASOURCE_REPLICA_PASSWORD=db_secure2026
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-primary:
        condition: service_healthy
      db-replica:
        condition: service_healthy
    networks:
      - pulse_net

  worker3:
    build:
      context: ./pulsealert-worker
    container_name: pulse_worker3
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DB_HOST=db-primary
      - WORKER_ID=3
      - WORKER_NEXT_URL=http://worker1:8080 # Fecha o anel
      - SPRING_DATASOURCE_PRIMARY_JDBC_URL=jdbc:postgresql://db-primary:5432/pulsealert
      - SPRING_DATASOURCE_PRIMARY_USERNAME=db_admin
      - SPRING_DATASOURCE_PRIMARY_PASSWORD=db_secure2026
      - SPRING_DATASOURCE_REPLICA_JDBC_URL=jdbc:postgresql://db-replica:5432/pulsealert
      - SPRING_DATASOURCE_REPLICA_USERNAME=db_admin
      - SPRING_DATASOURCE_REPLICA_PASSWORD=db_secure2026
    depends_on:
      rabbitmq:
        condition: service_healthy
      db-primary:
        condition: service_healthy
      db-replica:
        condition: service_healthy
    networks:
      - pulse_net

networks:
  pulse_net:
    driver: bridge