syntax = "proto3";

package pulsealert;

option java_multiple_files = true;
option java_package = "org.multivix.pulsealert.grpc";
option java_outer_classname = "PulseAlertProto";

service PulseAlertService {
  rpc SendVitalSign(VitalSignRequest) returns (VitalSignResponse);
}

message VitalSignRequest {
  string event_id = 1;
  string correlation_id = 2;
  string bed_id = 3;

  double heart_rate = 4;
  double spo2 = 5;
  double systolic_pressure = 6;
  double diastolic_pressure = 7;
  double temperature = 8;
}

message VitalSignResponse {
  string event_id = 1;
  string status = 2;
  string message = 3;
}